# Known alias mappings for Nazi-era German historical documents (1919-1945).

from __future__ import annotations

# 1. NSDAP
_NSDAP: dict[str, str] = {
    "NSDAP": "NSDAP",
    "N.S.D.A.P.": "NSDAP",
    "N.S.D.A.P": "NSDAP",
    "Nationalsozialistische Deutsche Arbeiterpartei": "NSDAP",
    "National Socialist German Workers' Party": "NSDAP",
    "National Socialist German Workers Party": "NSDAP",
    "Nazi Party": "NSDAP",
    "Nazi party": "NSDAP",
    "the Nazi Party": "NSDAP",
    "Nationalsozialisten": "NSDAP",
    "Nationalsozialist": "NSDAP",
    "National Socialists": "NSDAP",
    "National Socialist Party": "NSDAP",
    "NS-Partei": "NSDAP",
    "die Partei": "NSDAP",
    "the Party": "NSDAP",
    "Hitler Party": "NSDAP",
    "Hitlerpartei": "NSDAP",
    "DAP": "NSDAP",
    "Deutsche Arbeiterpartei": "NSDAP",
    "German Workers' Party": "NSDAP",
    # generic + inflected/spaced German forms that recur in the letters
    "Partei": "NSDAP",
    "die Bewegung": "NSDAP",
    "Bewegung": "NSDAP",
    "Nationalsozialismus": "NSDAP",
    "nationalsozialistische Bewegung": "NSDAP",
    "Nationalsozialistische Partei": "NSDAP",
    "Nationalsozialistische Deutsche Arbeiter Partei": "NSDAP",
    "Nationalsozialistischen Deutschen Arbeiterpartei": "NSDAP",
    "Nationalsozialistischen Deutschen Arbeiter Partei": "NSDAP",
    "Nationalsozialistische Deutsche Arbeiterpartei (NSDAP)": "NSDAP",
    "Nationalistische Deutsche Arbeiterpartei": "NSDAP",
    "Partei Hitler": "NSDAP",
    "Hitlerbewegung": "NSDAP",
}

# 2. SA (Sturmabteilung)
_SA: dict[str, str] = {
    "SA": "SA (Sturmabteilung)",
    "S.A.": "SA (Sturmabteilung)",
    "Sturmabteilung": "SA (Sturmabteilung)",
    "Sturmabteilungen": "SA (Sturmabteilung)",
    "Storm Troopers": "SA (Sturmabteilung)",
    "Storm Troops": "SA (Sturmabteilung)",
    "Stormtroopers": "SA (Sturmabteilung)",
    "Brownshirts": "SA (Sturmabteilung)",
    "Brown Shirts": "SA (Sturmabteilung)",
    "Braunhemden": "SA (Sturmabteilung)",
    "Brown Shirt": "SA (Sturmabteilung)",
    "the SA": "SA (Sturmabteilung)",
    "SA-Männer": "SA (Sturmabteilung)",
    "SA men": "SA (Sturmabteilung)",
}

# 3. SS (Schutzstaffel)
_SS: dict[str, str] = {
    "SS": "SS (Schutzstaffel)",
    "S.S.": "SS (Schutzstaffel)",
    "Schutzstaffel": "SS (Schutzstaffel)",
    "Schutzstaffeln": "SS (Schutzstaffel)",
    "the SS": "SS (Schutzstaffel)",
    "Blackshirts": "SS (Schutzstaffel)",
    "Black Shirts": "SS (Schutzstaffel)",
    "Allgemeine SS": "SS (Schutzstaffel)",
    "Waffen-SS": "SS (Schutzstaffel)",
    "SS-Männer": "SS (Schutzstaffel)",
    "SS men": "SS (Schutzstaffel)",
}

# 4. SPD
_SPD: dict[str, str] = {
    "SPD": "SPD",
    "S.P.D.": "SPD",
    "Sozialdemokratische Partei Deutschlands": "SPD",
    "Social Democratic Party": "SPD",
    "Social Democratic Party of Germany": "SPD",
    "Social Democrats": "SPD",
    "Sozialdemokraten": "SPD",
    "Sozialdemokratie": "SPD",
    "Social Democracy": "SPD",
    "Majority Social Democrats": "SPD",
    "MSPD": "SPD",
}

# 5. KPD
_KPD: dict[str, str] = {
    "KPD": "KPD",
    "K.P.D.": "KPD",
    "Kommunistische Partei Deutschlands": "KPD",
    "Communist Party": "KPD",
    "Communist Party of Germany": "KPD",
    "German Communist Party": "KPD",
    "Communists": "KPD",
    "Kommunisten": "KPD",
    "Spartacists": "KPD",
    "Spartakusbund": "KPD",
    "Spartacus League": "KPD",
    "the Reds": "KPD",
    "kommunistische Partei": "KPD",
    "Kommunistischen Partei": "KPD",
    "Kommunistische Partei (KPD)": "KPD",
    "Komunisten": "KPD",
}

# 6. DNVP
_DNVP: dict[str, str] = {
    "DNVP": "DNVP",
    "D.N.V.P.": "DNVP",
    "Deutschnationale Volkspartei": "DNVP",
    "German National People's Party": "DNVP",
    "German Nationalists": "DNVP",
    "Deutschnationale": "DNVP",
    "Deutschnationalen": "DNVP",
    "Deutschnationaler": "DNVP",
    "Deutschnationale Partei": "DNVP",
    "Nationalists": "DNVP",
}

# 7. Center Party (Zentrum)
_CENTER: dict[str, str] = {
    "Zentrum": "Center Party (Zentrum)",
    "Center Party": "Center Party (Zentrum)",
    "Centre Party": "Center Party (Zentrum)",
    "Deutsche Zentrumspartei": "Center Party (Zentrum)",
    "Zentrumspartei": "Center Party (Zentrum)",
    "Catholic Center Party": "Center Party (Zentrum)",
}

# 8. Other organizations (~40)
_OTHER_ORGS: dict[str, str] = {
    # Stahlhelm
    "Stahlhelm": "Stahlhelm",
    "Der Stahlhelm": "Stahlhelm",
    "Stahlhelm, Bund der Frontsoldaten": "Stahlhelm",
    "Steel Helmet": "Stahlhelm",
    "Steel Helmets": "Stahlhelm",
    "League of Front Soldiers": "Stahlhelm",
    # Freikorps
    "Freikorps": "Freikorps",
    "Free Corps": "Freikorps",
    "Freecorps": "Freikorps",
    "Freikorps units": "Freikorps",
    # Hitler Youth
    "HJ": "Hitler Youth (Hitlerjugend)",
    "H.J.": "Hitler Youth (Hitlerjugend)",
    "Hitlerjugend": "Hitler Youth (Hitlerjugend)",
    "Hitler Youth": "Hitler Youth (Hitlerjugend)",
    "Hitler-Jugend": "Hitler Youth (Hitlerjugend)",
    # BDM
    "BDM": "League of German Girls (BDM)",
    "B.D.M.": "League of German Girls (BDM)",
    "Bund Deutscher Mädel": "League of German Girls (BDM)",
    "Bund Deutscher Maedel": "League of German Girls (BDM)",
    "League of German Girls": "League of German Girls (BDM)",
    # NSKK
    "NSKK": "NSKK",
    "Nationalsozialistisches Kraftfahrkorps": "NSKK",
    "National Socialist Motor Corps": "NSKK",
    # NSFK
    "NSFK": "NSFK",
    "Nationalsozialistisches Fliegerkorps": "NSFK",
    "National Socialist Flyers Corps": "NSFK",
    # DAF
    "DAF": "German Labor Front (DAF)",
    "D.A.F.": "German Labor Front (DAF)",
    "Deutsche Arbeitsfront": "German Labor Front (DAF)",
    "German Labour Front": "German Labor Front (DAF)",
    "German Labor Front": "German Labor Front (DAF)",
    "Labor Front": "German Labor Front (DAF)",
    # NSV
    "NSV": "NSV",
    "Nationalsozialistische Volkswohlfahrt": "NSV",
    "National Socialist People's Welfare": "NSV",
    # NSBO
    "NSBO": "NSBO",
    "Nationalsozialistische Betriebszellenorganisation": "NSBO",
    # SS-related / police
    "Gestapo": "Gestapo",
    "Geheime Staatspolizei": "Gestapo",
    "Secret State Police": "Gestapo",
    "SD": "SD (Sicherheitsdienst)",
    "Sicherheitsdienst": "SD (Sicherheitsdienst)",
    "Security Service": "SD (Sicherheitsdienst)",
    # Reichsbanner (SPD paramilitary)
    "Reichsbanner": "Reichsbanner Schwarz-Rot-Gold",
    "Reichsbanner Schwarz-Rot-Gold": "Reichsbanner Schwarz-Rot-Gold",
    "Reichsbanner Black-Red-Gold": "Reichsbanner Schwarz-Rot-Gold",
    # Rotfrontkämpferbund (KPD paramilitary)
    "Rotfrontkämpferbund": "Rotfrontkämpferbund",
    "Rotfrontkaempferbund": "Rotfrontkämpferbund",
    "RFB": "Rotfrontkämpferbund",
    "Red Front Fighters' League": "Rotfrontkämpferbund",
    "Red Front": "Rotfrontkämpferbund",
    # DDP / DVP
    "DDP": "DDP",
    "Deutsche Demokratische Partei": "DDP",
    "German Democratic Party": "DDP",
    "DVP": "DVP",
    "Deutsche Volkspartei": "DVP",
    "German People's Party": "DVP",
    # Thule, Pan-German
    "Thule Society": "Thule Society",
    "Thule-Gesellschaft": "Thule Society",
    "Pan-German League": "Pan-German League",
    "Alldeutscher Verband": "Pan-German League",
    # Reichswehr / Wehrmacht orgs (also institutional)
    "Frontbann": "Frontbann",
}

# 9. Key figures (~70)
_FIGURES: dict[str, str] = {
    # Hitler
    "Hitler": "Adolf Hitler",
    "Adolf Hitler": "Adolf Hitler",
    "A. Hitler": "Adolf Hitler",
    "der Führer": "Adolf Hitler",
    "the Führer": "Adolf Hitler",
    "der Fuehrer": "Adolf Hitler",
    "the Fuehrer": "Adolf Hitler",
    "Führer": "Adolf Hitler",
    "dem Führer": "Adolf Hitler",
    "den Führer": "Adolf Hitler",
    "unser Führer": "Adolf Hitler",
    "unserem Führer": "Adolf Hitler",
    # Goebbels
    "Goebbels": "Joseph Goebbels",
    "Joseph Goebbels": "Joseph Goebbels",
    "Josef Goebbels": "Joseph Goebbels",
    "Dr. Goebbels": "Joseph Goebbels",
    # Himmler
    "Himmler": "Heinrich Himmler",
    "Heinrich Himmler": "Heinrich Himmler",
    "Reichsführer Himmler": "Heinrich Himmler",
    # Göring
    "Göring": "Hermann Göring",
    "Goering": "Hermann Göring",
    "Hermann Göring": "Hermann Göring",
    "Hermann Goering": "Hermann Göring",
    # Röhm
    "Röhm": "Ernst Röhm",
    "Roehm": "Ernst Röhm",
    "Ernst Röhm": "Ernst Röhm",
    "Ernst Roehm": "Ernst Röhm",
    # Strasser
    "Strasser": "Gregor Strasser",
    "Gregor Strasser": "Gregor Strasser",
    "Otto Strasser": "Otto Strasser",
    # Hindenburg
    "Hindenburg": "Paul von Hindenburg",
    "Paul von Hindenburg": "Paul von Hindenburg",
    "von Hindenburg": "Paul von Hindenburg",
    "Field Marshal Hindenburg": "Paul von Hindenburg",
    "President Hindenburg": "Paul von Hindenburg",
    "Reichspräsident Hindenburg": "Paul von Hindenburg",
    # Bismarck
    "Bismarck": "Otto von Bismarck",
    "Otto von Bismarck": "Otto von Bismarck",
    "von Bismarck": "Otto von Bismarck",
    # Kaiser Wilhelm II
    "Kaiser Wilhelm": "Kaiser Wilhelm II",
    "Wilhelm II": "Kaiser Wilhelm II",
    "Kaiser Wilhelm II": "Kaiser Wilhelm II",
    "the Kaiser": "Kaiser Wilhelm II",
    "Emperor Wilhelm": "Kaiser Wilhelm II",
    "Kaiser": "Kaiser Wilhelm II",
    # Horst Wessel
    "Horst Wessel": "Horst Wessel",
    "Wessel": "Horst Wessel",
    # Ebert
    "Ebert": "Friedrich Ebert",
    "Friedrich Ebert": "Friedrich Ebert",
    # Lenin
    "Lenin": "Vladimir Lenin",
    "Vladimir Lenin": "Vladimir Lenin",
    "W. I. Lenin": "Vladimir Lenin",
    # Marx
    "Marx": "Karl Marx",
    "Karl Marx": "Karl Marx",
    # Ludendorff
    "Ludendorff": "Erich Ludendorff",
    "Erich Ludendorff": "Erich Ludendorff",
    "General Ludendorff": "Erich Ludendorff",
    # Rosenberg
    "Rosenberg": "Alfred Rosenberg",
    "Alfred Rosenberg": "Alfred Rosenberg",
    # Streicher
    "Streicher": "Julius Streicher",
    "Julius Streicher": "Julius Streicher",
    # Ley
    "Ley": "Robert Ley",
    "Robert Ley": "Robert Ley",
    "Dr. Ley": "Robert Ley",
    # Hess
    "Hess": "Rudolf Hess",
    "Heß": "Rudolf Hess",
    "Rudolf Hess": "Rudolf Hess",
    "Rudolf Heß": "Rudolf Hess",
    # Bormann
    "Bormann": "Martin Bormann",
    "Martin Bormann": "Martin Bormann",
    # Feder
    "Feder": "Gottfried Feder",
    "Gottfried Feder": "Gottfried Feder",
    # Rathenau
    "Rathenau": "Walther Rathenau",
    "Walther Rathenau": "Walther Rathenau",
    "Walter Rathenau": "Walther Rathenau",
    # Stresemann
    "Stresemann": "Gustav Stresemann",
    "Gustav Stresemann": "Gustav Stresemann",
    # Brüning
    "Brüning": "Heinrich Brüning",
    "Bruening": "Heinrich Brüning",
    "Heinrich Brüning": "Heinrich Brüning",
    "Chancellor Brüning": "Heinrich Brüning",
    # Papen
    "Papen": "Franz von Papen",
    "von Papen": "Franz von Papen",
    "Franz von Papen": "Franz von Papen",
    # Schleicher
    "Schleicher": "Kurt von Schleicher",
    "von Schleicher": "Kurt von Schleicher",
    "Kurt von Schleicher": "Kurt von Schleicher",
    "General von Schleicher": "Kurt von Schleicher",
    # Hugenberg
    "Hugenberg": "Alfred Hugenberg",
    "Alfred Hugenberg": "Alfred Hugenberg",
    # Schirach
    "Schirach": "Baldur von Schirach",
    "Baldur von Schirach": "Baldur von Schirach",
    "von Schirach": "Baldur von Schirach",
    # Heydrich
    "Heydrich": "Reinhard Heydrich",
    "Reinhard Heydrich": "Reinhard Heydrich",
    # Speer
    "Speer": "Albert Speer",
    "Albert Speer": "Albert Speer",
    # A few more recurrent names in the Abel corpus
    "Drexler": "Anton Drexler",
    "Anton Drexler": "Anton Drexler",
    "Eckart": "Dietrich Eckart",
    "Dietrich Eckart": "Dietrich Eckart",
    "Frick": "Wilhelm Frick",
    "Wilhelm Frick": "Wilhelm Frick",
    "Darré": "Richard Walther Darré",
    "Darre": "Richard Walther Darré",
    "Liebknecht": "Karl Liebknecht",
    "Karl Liebknecht": "Karl Liebknecht",
    "Rosa Luxemburg": "Rosa Luxemburg",
    "Luxemburg": "Rosa Luxemburg",
    "Scheidemann": "Philipp Scheidemann",
    "Philipp Scheidemann": "Philipp Scheidemann",
    "Thälmann": "Ernst Thälmann",
    "Thaelmann": "Ernst Thälmann",
    "Ernst Thälmann": "Ernst Thälmann",
}

# 10. Locations (German <-> English) (~110)
_LOCATIONS: dict[str, str] = {
    # Major cities
    "München": "Munich",
    "Muenchen": "Munich",
    "Munich": "Munich",
    "Köln": "Cologne",
    "Koeln": "Cologne",
    "Cologne": "Cologne",
    "Nürnberg": "Nuremberg",
    "Nuernberg": "Nuremberg",
    "Nuremberg": "Nuremberg",
    "Wien": "Vienna",
    "Vienna": "Vienna",
    "Berlin": "Berlin",
    "Hamburg": "Hamburg",
    "Frankfurt": "Frankfurt am Main",
    "Frankfurt am Main": "Frankfurt am Main",
    "Frankfurt a.M.": "Frankfurt am Main",
    "Stuttgart": "Stuttgart",
    "Düsseldorf": "Düsseldorf",
    "Duesseldorf": "Düsseldorf",
    "Dresden": "Dresden",
    "Leipzig": "Leipzig",
    "Hannover": "Hanover",
    "Hanover": "Hanover",
    "Bremen": "Bremen",
    "Essen": "Essen",
    "Dortmund": "Dortmund",
    "Duisburg": "Duisburg",
    "Mannheim": "Mannheim",
    "Karlsruhe": "Karlsruhe",
    "Kassel": "Kassel",
    "Braunschweig": "Brunswick",
    "Brunswick": "Brunswick",
    "Kiel": "Kiel",
    "Lübeck": "Lübeck",
    "Luebeck": "Lübeck",
    "Augsburg": "Augsburg",
    "Würzburg": "Würzburg",
    "Wuerzburg": "Würzburg",
    "Regensburg": "Regensburg",
    "Weimar": "Weimar",
    "Jena": "Jena",
    "Halle": "Halle",
    "Magdeburg": "Magdeburg",
    "Chemnitz": "Chemnitz",
    "Bonn": "Bonn",
    "Aachen": "Aachen",
    "Aix-la-Chapelle": "Aachen",
    "Mainz": "Mainz",
    "Wiesbaden": "Wiesbaden",
    "Koblenz": "Koblenz",
    "Trier": "Trier",
    "Freiburg": "Freiburg",
    "Heidelberg": "Heidelberg",
    "Potsdam": "Potsdam",
    "Erfurt": "Erfurt",
    "Rostock": "Rostock",
    "Königsberg": "Königsberg",
    "Koenigsberg": "Königsberg",
    "Breslau": "Breslau",
    "Stettin": "Stettin",
    "Danzig": "Danzig",
    "Gdansk": "Danzig",
    "Memel": "Memel",
    # German states / regions
    "Bayern": "Bavaria",
    "Bavaria": "Bavaria",
    "Preußen": "Prussia",
    "Preussen": "Prussia",
    "Prussia": "Prussia",
    "Sachsen": "Saxony",
    "Saxony": "Saxony",
    "Württemberg": "Württemberg",
    "Wuerttemberg": "Württemberg",
    "Baden": "Baden",
    "Thüringen": "Thuringia",
    "Thueringen": "Thuringia",
    "Thuringia": "Thuringia",
    "Hessen": "Hesse",
    "Hesse": "Hesse",
    "Rheinland": "Rhineland",
    "Rhineland": "Rhineland",
    "Westfalen": "Westphalia",
    "Westphalia": "Westphalia",
    "Schlesien": "Silesia",
    "Silesia": "Silesia",
    "Pommern": "Pomerania",
    "Pomerania": "Pomerania",
    "Ostpreußen": "East Prussia",
    "Ostpreussen": "East Prussia",
    "East Prussia": "East Prussia",
    "Ruhrgebiet": "Ruhr",
    "Ruhr": "Ruhr",
    "the Ruhr": "Ruhr",
    "Saarland": "Saar",
    "Saar": "Saar",
    "the Saar": "Saar",
    "Rheinland-Pfalz": "Rhineland-Palatinate",
    "Mecklenburg": "Mecklenburg",
    "Oldenburg": "Oldenburg",
    "Anhalt": "Anhalt",
    "Franken": "Franconia",
    "Franconia": "Franconia",
    "Schwaben": "Swabia",
    "Swabia": "Swabia",
    # Countries / neighbors
    "Deutschland": "Germany",
    "Deutschlands": "Germany",
    "Germany": "Germany",
    "Österreich": "Austria",
    "Oesterreich": "Austria",
    "Austria": "Austria",
    "Frankreich": "France",
    "France": "France",
    "England": "England",
    "Großbritannien": "Great Britain",
    "Grossbritannien": "Great Britain",
    "Great Britain": "Great Britain",
    "Russland": "Russia",
    "Russia": "Russia",
    "Sowjetunion": "Soviet Union",
    "Soviet Union": "Soviet Union",
    "USSR": "Soviet Union",
    "UdSSR": "Soviet Union",
    "Polen": "Poland",
    "Poland": "Poland",
    "Italien": "Italy",
    "Italy": "Italy",
    "Belgien": "Belgium",
    "Belgium": "Belgium",
    "Niederlande": "Netherlands",
    "Holland": "Netherlands",
    "Netherlands": "Netherlands",
    "Tschechoslowakei": "Czechoslovakia",
    "Czechoslovakia": "Czechoslovakia",
    "Schweiz": "Switzerland",
    "Switzerland": "Switzerland",
    "Ungarn": "Hungary",
    "Hungary": "Hungary",
    "Dänemark": "Denmark",
    "Daenemark": "Denmark",
    "Denmark": "Denmark",
    "USA": "United States",
    "Vereinigte Staaten": "United States",
    "United States": "United States",
    "America": "United States",
    "Amerika": "United States",
    # Demonyms - the people stand in for the country in these narratives.
    "Vaterland": "Germany",
    "Vaterlandes": "Germany",
    "das Vaterland": "Germany",
    "Deutsche": "Germany",
    "Franzosen": "France",
    "die Franzosen": "France",
    "Engländer": "England",
    "Russen": "Russia",
    "Italiener": "Italy",
}

# 11. Events (~45)
_EVENTS: dict[str, str] = {
    # World War I
    "World War I": "World War I",
    "World War One": "World War I",
    "First World War": "World War I",
    "WWI": "World War I",
    "WW1": "World War I",
    "the Great War": "World War I",
    "Great War": "World War I",
    "Weltkrieg": "World War I",
    "der Weltkrieg": "World War I",
    "Erster Weltkrieg": "World War I",
    "the World War": "World War I",
    "Krieg": "World War I",
    "der Krieg": "World War I",
    "Revolution": "November Revolution (1918)",
    "die Revolution": "November Revolution (1918)",
    # Machtergreifung / seizure of power
    "Machtergreifung": "Seizure of Power (1933)",
    "Machtübernahme": "Seizure of Power (1933)",
    "Machtuebernahme": "Seizure of Power (1933)",
    "Seizure of Power": "Seizure of Power (1933)",
    "seizure of power": "Seizure of Power (1933)",
    "the takeover": "Seizure of Power (1933)",
    # Beer Hall Putsch
    "Beer Hall Putsch": "Beer Hall Putsch (1923)",
    "Beer-Hall Putsch": "Beer Hall Putsch (1923)",
    "Hitlerputsch": "Beer Hall Putsch (1923)",
    "Hitler Putsch": "Beer Hall Putsch (1923)",
    "Hitler-Putsch": "Beer Hall Putsch (1923)",
    "Münchener Putsch": "Beer Hall Putsch (1923)",
    "Munich Putsch": "Beer Hall Putsch (1923)",
    "Bürgerbräu Putsch": "Beer Hall Putsch (1923)",
    # November Revolution
    "November Revolution": "November Revolution (1918)",
    "Novemberrevolution": "November Revolution (1918)",
    "the Revolution": "November Revolution (1918)",
    "November 1918": "November Revolution (1918)",
    # Treaty of Versailles
    "Treaty of Versailles": "Treaty of Versailles",
    "Versailles Treaty": "Treaty of Versailles",
    "Versailler Vertrag": "Treaty of Versailles",
    "Versailles": "Treaty of Versailles",
    "the Diktat": "Treaty of Versailles",
    "Versailles Diktat": "Treaty of Versailles",
    "Friedensvertrag von Versailles": "Treaty of Versailles",
    # Hyperinflation
    "Hyperinflation": "Inflation of 1923",
    "the inflation": "Inflation of 1923",
    "Inflation": "Inflation of 1923",
    "Inflationszeit": "Inflation of 1923",
    # Kapp Putsch
    "Kapp Putsch": "Kapp Putsch (1920)",
    "Kapp-Putsch": "Kapp Putsch (1920)",
    # Reichstag Fire
    "Reichstag Fire": "Reichstag Fire (1933)",
    "Reichstagsbrand": "Reichstag Fire (1933)",
    # Kristallnacht
    "Kristallnacht": "Kristallnacht (1938)",
    "Night of Broken Glass": "Kristallnacht (1938)",
    "Reichspogromnacht": "Kristallnacht (1938)",
    # Night of the Long Knives
    "Night of the Long Knives": "Night of the Long Knives (1934)",
    "Night of Long Knives": "Night of the Long Knives (1934)",
    "Röhm Putsch": "Night of the Long Knives (1934)",
    "Roehm Putsch": "Night of the Long Knives (1934)",
    "Röhm-Putsch": "Night of the Long Knives (1934)",
    # World War II
    "World War II": "World War II",
    "Second World War": "World War II",
    "WWII": "World War II",
    "WW2": "World War II",
    "Zweiter Weltkrieg": "World War II",
    # Great Depression
    "Great Depression": "Great Depression",
    "Weltwirtschaftskrise": "Great Depression",
    "the Depression": "Great Depression",
    "Ruhr Occupation": "Occupation of the Ruhr (1923)",
    "Ruhrbesetzung": "Occupation of the Ruhr (1923)",
    "Occupation of the Ruhr": "Occupation of the Ruhr (1923)",
}

# 12. Military / institutional (~25)
_MILITARY_INSTITUTIONAL: dict[str, str] = {
    "Reichswehr": "Reichswehr",
    "the Reichswehr": "Reichswehr",
    "German Army": "German Army",
    "Deutsches Heer": "German Army",
    "das Heer": "German Army",
    "the Army": "German Army",
    "Militär": "German Army",
    "das Militär": "German Army",
    "Wehrmacht": "Wehrmacht",
    "the Wehrmacht": "Wehrmacht",
    "Prussian Army": "Prussian Army",
    "Preußische Armee": "Prussian Army",
    "Preussische Armee": "Prussian Army",
    "Kaiserliche Armee": "Imperial German Army",
    "Imperial Army": "Imperial German Army",
    "Imperial German Army": "Imperial German Army",
    "Reichsmarine": "Reichsmarine",
    "Kaiserliche Marine": "Imperial German Navy",
    "Imperial Navy": "Imperial German Navy",
    "Weimar Republic": "Weimar Republic",
    "Weimarer Republik": "Weimar Republic",
    "the Republic": "Weimar Republic",
    "Republik": "Weimar Republic",
    "die Republik": "Weimar Republic",
    "German Empire": "German Empire",
    "Deutsches Reich": "German Empire",
    "Kaiserreich": "German Empire",
    "Second Reich": "German Empire",
    "the Empire": "German Empire",
    "Third Reich": "Third Reich",
    "Drittes Reich": "Third Reich",
    "Reichstag": "Reichstag",
    "the Reichstag": "Reichstag",
    "Reichsrat": "Reichsrat",
    "Reichskanzlei": "Reich Chancellery",
    "Reich Chancellery": "Reich Chancellery",
    "Reichswehrministerium": "Reichswehr Ministry",
}

# 13. Venues, additional cities, and recurring publications/symbols (~25)
_VENUES_MISC: dict[str, str] = {
    # Munich venues central to NSDAP early history
    "Bürgerbräukeller": "Bürgerbräukeller (Munich)",
    "Buergerbraeukeller": "Bürgerbräukeller (Munich)",
    "Hofbräuhaus": "Hofbräuhaus (Munich)",
    "Hofbraeuhaus": "Hofbräuhaus (Munich)",
    "Feldherrnhalle": "Feldherrnhalle (Munich)",
    "Braunes Haus": "Brown House (Munich)",
    "Brown House": "Brown House (Munich)",
    "Sportpalast": "Sportpalast (Berlin)",
    "Berlin Sportpalast": "Sportpalast (Berlin)",
    "Wilhelmstraße": "Wilhelmstraße (Berlin)",
    "Wilhelmstrasse": "Wilhelmstraße (Berlin)",
    "Reichstag building": "Reichstag",
    # Party press / publications
    "Völkischer Beobachter": "Völkischer Beobachter",
    "Voelkischer Beobachter": "Völkischer Beobachter",
    "VB": "Völkischer Beobachter",
    "Der Angriff": "Der Angriff",
    "Der Stürmer": "Der Stürmer",
    "Der Stuermer": "Der Stürmer",
    "Mein Kampf": "Mein Kampf",
    "Das Kapital": "Das Kapital",
    # Additional cities
    "Hof": "Hof",
    "Bamberg": "Bamberg",
    "Bayreuth": "Bayreuth",
    "Landshut": "Landshut",
    "Coburg": "Coburg",
    "Gera": "Gera",
    "Plauen": "Plauen",
    "Görlitz": "Görlitz",
    "Goerlitz": "Görlitz",
    "Bochum": "Bochum",
    "Wuppertal": "Wuppertal",
    "Krefeld": "Krefeld",
    "Münster": "Münster",
    "Muenster": "Münster",
}

# Merge all categories into the single ALIASES export.
_CATEGORY_DICTS: list[dict[str, str]] = [
    _NSDAP, _SA, _SS, _SPD, _KPD, _DNVP, _CENTER, _OTHER_ORGS,
    _FIGURES, _LOCATIONS, _EVENTS, _MILITARY_INSTITUTIONAL, _VENUES_MISC,
]

ALIASES: dict[str, str] = {}
for _d in _CATEGORY_DICTS:
    ALIASES.update(_d)

# Total count is available for tests / diagnostics.
ALIAS_COUNT: int = len(ALIASES)

# Public/historical figures (Hitler, Marx, Hindenburg, ...). Tagged in the graph
# as reference figures so they can be separated from authors' lived contacts.
REFERENCE_FIGURES: set[str] = set(_FIGURES.values())
